# This file is a template, and might need editing before it works on your project.
# Official docker image.

before_script:
- docker info
- git submodule update --init --recursive

build:
  stage: build
  tags:
    - shell-runner
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.ii.org.nz
  - docker build -t docker.ii.org.nz/ii/encrypt-everything:nginx-proxy docker-nginx/mainline/jessie/
  - docker build -t docker.ii.org.nz/ii/encrypt-everything:docker-gen docker-gen/
  - docker build -t docker.ii.org.nz/ii/encrypt-everything:nginx-letsencrypt docker-letsencrypt-nginx-proxy-companion/
  - docker push docker.ii.org.nz/ii/encrypt-everything:nginx-proxy
  - docker push docker.ii.org.nz/ii/encrypt-everything:docker-gen
  - docker push docker.ii.org.nz/ii/encrypt-everything:nginx-letsencrypt