version: '2'
services:
  nginx:
    image: docker.ii.org.nz/ii/encrypt-everything:nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./volumes/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: docker.ii.org.nz/ii/encrypt-everything:docker-gen
    container_name: nginx-gen
    command: -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - ./volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: docker.ii.org.nz/ii/encrypt-everything:nginx-letsencrypt 
    container_name: nginx-letsencrypt
    volumes_from:
      - nginx
    volumes:
      - ./volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
